name: "Install Dependencies"
description: "Install nodejs dependencies and verify their provenance"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"

    - name: Install dependencies
      run: npm ci

    - name: Verify dependencies provenance
      run: npm audit signatures
