name: Feature Branch

on:
  pull_request:
    types:
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  clean-deployment:
    if: github.event.action == 'closed' && github.event.pull_request.draft == false
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          custom-url: percoct-ui.yld.engineering
