name: Feature Branch Closed

on:
  pull_request:
    types:
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  clean-deployment:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          custom-url: percoct-ui.yld.engineering
